name: cfvgbhjk

on:
  issue_comment:
    types:
      - created
jobs:
  bababa:
    uses: yosiroute/grijhenzui/.github/workflows/ojewqw-base.yml@main
    with:
      project_number: 582
      github_token: ${{ secrets.TEST_ACCESS_TOKEN }}
    secrets: inherit

